[package]
name = "goldparser_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
utf16string = "0.2.0"
enum_primitive = "0.1"
num-traits = "0.2"
#rmp = "0.8"
